#!/bin/bash
# DNS CNAME Update für kurs.prostarmarketing.de → Railway

echo "🔄 DNS CNAME Update wird vorbereitet..."
echo ""
echo "WICHTIG: Du musst dies MANUELL bei Google Domains machen!"
echo ""
echo "📋 SCHRITT-FÜR-SCHRITT:"
echo ""
echo "1. Öffne: https://domains.google.com"
echo "2. Wähle Domain: prostarmarketing.de"
echo "3. Klicke: DNS (linke Seite)"
echo "4. Scrolle zu: Custom resource records"
echo ""
echo "5. FINDE den Eintrag:"
echo "   Name:  kurs"
echo "   Type:  CNAME"
echo "   Data:  ext-sq.squarespace.com  ← DIESER MUSS WEG!"
echo ""
echo "6. KLICKE auf den EDIT-Button (Stift-Symbol)"
echo ""
echo "7. ÄNDERE 'Data' zu:"
echo "   prostarlandingpage-1-production.up.railway.app"
echo ""
echo "8. SPEICHERN!"
echo ""
echo "✅ Nach dem Speichern:"
echo "   - Warte 15-30 Minuten (DNS Propagation)"
echo "   - Dann Custom Domain in Railway hinzufügen"
echo ""
echo "🔍 DNS-Status prüfen:"
echo "   dig kurs.prostarmarketing.de CNAME +short"
echo ""
echo "Erwartete Ausgabe nach Änderung:"
echo "   prostarlandingpage-1-production.up.railway.app."
echo ""
