#!/bin/bash
# Railway Custom Domain Setup

echo "🚀 Railway Custom Domain Setup"
echo ""
echo "⚠️  WICHTIG: Mache dies ERST NACHDEM DNS propagiert ist!"
echo ""
echo "📋 ANLEITUNG:"
echo ""
echo "1. Öffne Railway Dashboard:"
echo "   https://railway.app/project/fb2b6a6c-c10b-4192-89fa-b071b761f619"
echo ""
echo "2. Klicke auf Service: prostar_landing_page--1-"
echo ""
echo "3. Klicke: Settings (oben rechts)"
echo ""
echo "4. Links: Domains"
echo ""
echo "5. Klicke: 'Custom Domain' Button"
echo ""
echo "6. Eingeben: kurs.prostarmarketing.de"
echo ""
echo "7. Klicke: Add"
echo ""
echo "✅ Railway wird jetzt:"
echo "   - DNS-Konfiguration prüfen"
echo "   - SSL-Zertifikat generieren (Let's Encrypt)"
echo "   - Domain aktivieren"
echo ""
echo "⏳ Status-Check:"
echo "   - Grünes Häkchen = SSL aktiv, fertig!"
echo "   - Orange Warnung = DNS noch nicht propagiert, warte"
echo "   - Rotes X = DNS falsch, prüfe CNAME"
echo ""
echo "🔍 DNS MUSS vorher zeigen:"
echo "   kurs.prostarmarketing.de → prostarlandingpage-1-production.up.railway.app"
echo ""
echo "Test mit:"
echo "   dig kurs.prostarmarketing.de CNAME +short"
echo ""
